#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Build a Python virtual environment without setuptools, virtualenv and
other dependencies. Useful when building on "fresh" systems or those
which for some reason do not have the required dependencies available

Support Python 2.6, Python 2.7, and Python 3
See Makefile ...
TODO(AG): Split into 2.x branch and 3.x branch. 2.x is moribund and
          it is not worth all of the complexity in this file and the
          the Makefile to maintain both when 2.x is barely used

Copyright (C) 2018
    Adam Greene <copyright@mzpqnxow.com>
    David Marker <dave@freedave.net>
Please see LICENSE or LICENSE.md for terms
"""
import subprocess
import multiprocessing
from os import mkdir, getuid, getcwd, environ, chdir, symlink, remove, unlink
from os.path import dirname, realpath, join as join_path, abspath
from datetime import datetime
import pwd
import shutil
from contextlib import contextmanager
from errno import EEXIST, ENOENT, ENOTEMPTY
from time import sleep
from os.path import (isdir, exists, sep as DIRSEP)
import sys
from shutil import which

RUNNING_PYTHON_VERSION = sys.version_info[0]

assert RUNNING_PYTHON_VERSION == 3

from configparser import ConfigParser, NoOptionError, NoSectionError

CURDIR = cwd = dirname(abspath(__file__))
# Basic required directories for a virtualenv
VENV_DIRS = set(['lib', 'bin', 'include'])
PIP_CONF = 'pip.conf'
# Taken from etc/
INI_FILES = set(['.interactive', PIP_CONF])
# Put your dependencies in these files in your empty venv directory
PKG_REQUIREMENT_FILEPATHS = set(['requirements.txt'])
PKG_CONSTRAINT_FILEPATHS = set(['constraints.txt'])

# By default, use the 'system python'
DEFAULT_VENV_BASE_PYTHON = which('python3')
CPU_COUNT = multiprocessing.cpu_count()
PYVERSION = 3

def pip_proxy():
    """Parse pip.conf to get proxy settings to pass on to easy_install

    This is a little bit controversial because we make some decisions
    without the consent of the user. We set parallelism options in
    case native code comes into play and we honor pip.ini proxy
    settings as well as proxy settings in the environment. The reason
    for honoring pip.ini proxy settings (manually) is to work around
    a somewhat rare (but not theoretical) bug where easy_install is
    invoked during pip. If pip has a proxy set in pip.ini, it does
    not get honored by easy_install, causing dependency fetches to
    fail in environments with hard requirements for a proxy. The
    best example of this is pandas, which is a pretty common package.

    To reproduce failure, set your proxy in pip.ini in an environment
    where a proxy is *REQUIRED* and try to pip install pandas. It will
    bomb out, saying it can't get numpy.

    Rather than making the user specify the proxy in pip.ini AND in the
    environment, we read pip.ini and set it in the environment for
    easy_install to consume.

    This approach fixes that.
    """
    config = ConfigParser()
    config.read(PIP_CONF)
    try:
        proxy = config.get('global', 'proxy')
    except (NoSectionError, NoOptionError):
        proxy = None
    return proxy


def basic_env(cwd, parallel=True, easy_install_proxy=True):
    """Provide a clean environment with bare essentials"""
    global PYVERSION
    pent = pwd.getpwuid(getuid())
    env = dict()
    env['PYTHONPATH'] = '{}/packages/lib/python{}/site-packages/'.format(
        cwd, PYVERSION)
    env['HOME'] = pent.pw_dir
    env['SHELL'] = pent.pw_shell
    env['LOGNAME'] = pent.pw_name
    env['PWD'] = getcwd()
    # One can hope that these environment variables make it to a compiled
    # native code build that uses GNU make. Pretty unlikely to work, and
    # even less likely to occur, but doesn't hurt. Maybe cython or pandas
    # or some such thing can benefit.. well, not pandas/cython, yet,
    # but maybe some day. Pandas currently takes 7 minutes to build from
    # source on "unsupported" platforms, but can not at this time benefit
    # from parallelism
    #
    # https://github.com/pandas-dev/pandas/issues/24344
    #
    if parallel is True:
        parallelism_count = '{}'.format(
            (CPU_COUNT)) if CPU_COUNT == 1 else '{}'.format(CPU_COUNT - 1)
        env['MAKEFLAGS'] = '-j{}'.format(parallelism_count)
        env['CONCURRENCY_LEVEL'] = parallelism_count

    if easy_install_proxy is True:
        # For edgecases where pip invokes easy_install and proxy is only
        # set in pip.ini, not in the environment
        proxy = pip_proxy()
        if proxy:  # Note: this overrides the environment with pip config
            environ['http_proxy'] = proxy
            environ['https_proxy'] = proxy

    for key in ('PATH', 'TERM', 'MAIL', 'http_proxy', 'https_proxy'):
        if key in environ:
            env[key] = environ[key]
    return env


@contextmanager
def pushd(directory):
    """ Emulate Bash pushd/popd """
    cwd = getcwd()
    try:
        chdir(directory)
    except OSError as err:
        if err.errno == ENOENT:
            raise RuntimeError('%s does not exist !!' % directory)
        else:
            raise err
    yield
    chdir(cwd)


def destroy(explain, vdirs, cfg):
    """ Destroy a previously created virtual environment """
    print('%s: destroying %s' % (explain, ('/ '.join(vdirs) + '/')))
    # rmtree can fail if there are stale .nfs files
    # so put it in a loop
    retry = 10  # don't try forever
    done = False
    while retry > 0 and not done:
        retry, done = (retry - 1, True)
        for directory in vdirs:
            try:
                shutil.rmtree(directory)
            except OSError as err:
                if err.errno == ENOENT:
                    pass  # directory already gone
                elif err.errno == ENOTEMPTY:
                    done = False  # try again if retry isn't exhausted.
                else:
                    raise err  # re-raise something is wrong.
        if not done:
            # SSHFS/NFS/CIFS/SMB or some other filesystem locking issue
            sleep(2)

    print('%s: destroying %s' % (explain, (' '.join(cfg))))
    for cfgfile in cfg:
        try:
            unlink(cfgfile)
        except (IOError, OSError):
            pass


def invoke_virtualenv(virtualenv_exe, python, pipini, interactive, cwd):
    """ Run virtualenv with the arguments and environment set """
    shutil.copy(pipini, 'pip.conf')
    shutil.copy(interactive, '.interactive')

    try:
        # subprocess.check_call([python, virtualenv_exe, '-p', python, '--no-site-packages', '.'],
        # --no-site-packages is now the default
        subprocess.check_call([python, virtualenv_exe, '--no-site-packages', '-p', python, '.'],
                              env=basic_env(cwd))
    except OSError as err:
        if err.errno == ENOENT:
            raise RuntimeError('Python %s does not exist !!' % python)
        else:
            raise err


def freeze(*args, **kwargs):
    pip(*args, **kwargs)


def install(*args, **kwargs):
    pip(*args, **kwargs)


def mkdir_p(dirname):
    """emulate mkdir -p behavior"""
    path_stack = ''
    for element in dirname.split(DIRSEP):
        if not isdir(dirname):
            if not element:
                continue
            path_stack = join_path(DIRSEP, path_stack, element)
            if not isdir(path_stack):
                mkdir(path_stack)


def pip(pip_exe, ini, require, constrain, cwd, action='install', parallel=True, easy_install_proxy=True):
    """
        Set 'PIP_CONFIG_FILE' environment variable to ini, then call
        exe as pip using the require file.
    """
    environ['PIP_CONFIG_FILE'] = ini

    req = None
    for req in require:
        if exists(req):
            break
    else:
        print('WARNING: none of %s exist, skipping pip' % (str(require)))
        return

    cst = None
    for cst in constrain:
        if exists(req):
            break
    else:
        cst = '/dev/null'

    pip_arguments = {
        'install': [  # Perform an install
            pip_exe, 'install', '--compile', '--progress-bar', 'off', '--pre',
            '-I', '-r', req, '-c', cst
        ],
        'freeze': [  # Freeze versions in a built venv
            pip_exe, 'freeze', '--no-cache-dir', '-l', '-r', req
        ]  # Preserves comments and order
    }
    assert action in (pip_arguments)

    if action == 'install':
        # Use -I to ensure prepackaged dependencies are installed if specified in
        # requirements.txt. Otherwise they are detected in the packages directory
        # and not installed at all, requiring manually adding with pip after the
        # venv is built
        try:
            subprocess.check_call(
                pip_arguments[action],
                env=basic_env(
                    cwd,
                    parallel=parallel,
                    easy_install_proxy=easy_install_proxy))
        except Exception as err:
            print('error invoking pip install {}'.format(err))
            raise
    elif action == 'freeze':
        try:
            byte_output = subprocess.check_output(
                pip_arguments[action], env=basic_env(cwd))
            frozen_fullpath = frozen_requirements_fullpath(req)
            with open(frozen_fullpath, 'wb') as ffd:
                ffd.write(byte_output)
                print('Writing stable, frozen requirements file to {}...'.
                      format(frozen_fullpath))
                print('# ---- END ---- #')
        except subprocess.CalledProcessError as err:
            print('error invoking pip freeze {}'.format(err))
            raise


def frozen_requirements_fullpath(req):
    base_requirements_path = (join_path(dirname(realpath(req))))
    mkdir_p(base_requirements_path)
    today_yyyymmdd = datetime.today().strftime('%Y-%m-%d.%S')
    frozen_filename = 'frozen-requirements-{}'.format(
        today_yyyymmdd)
    frozen_fullpath = '{}/{}'.format(base_requirements_path, frozen_filename)
    return frozen_fullpath


def main():
    """Let it begin"""
    # For 2.6 compatibility.. but we are off of 2.6 now, so why? ... deal with this later
    from optparse import OptionParser
    global DEFAULT_VENV_BASE_PYTHON, PYVERSION
    optparser = OptionParser('usage: %prog [options] <destination>')

    optparser.add_option(
        '-P',
        '--disable-parallel',
        action='store_false',
        default=True,
        dest='parallel',
        help='Attempt parallel builds for native packages')
    optparser.add_option(
        '-p',
        '--python',
        action='store',
        type='string',
        dest='python',
        default=DEFAULT_VENV_BASE_PYTHON,
        help='Specify the full path to python')
    optparser.add_option(
        '-e',
        '--disable-easy-install-proxy',
        action='store_false',
        dest='easy_install_proxy',
        default=True,
        help='Set http(s)_proxy in environment for easy_install to inherit')
    optparser.add_option(
        '--freeze',
        action='store_true',
        dest='freeze',
        default=False,
        help='Freeze versions in a venv for future stability (saves requirements.txt first)'
    )
    optparser.add_option(
        '-d',
        '--destroy',
        action='store_true',
        dest='destroy',
        default=False,
        help='Destroy a venv')
    optparser.add_option(
        '-i',
        '--ini',
        action='store',
        dest='inifile',
        default='pip.ini',
        help='The pip.ini file to use from the etc/ directory')

    (args, venv_dest) = optparser.parse_args()

    if not venv_dest:
        optparser.error('must specify destination')

    cwd = dirname(abspath(__file__))

    ini_load_path = join_path(cwd, 'etc/%s' % args.inifile)
    virtualenv_run_path = join_path(cwd, 'packages/bin/virtualenv')
    interactive_load_path = join_path(cwd, 'etc/interactive')

    try:
        with pushd(venv_dest[0]):
            if args.destroy:
                destroy('requested destroy and recreate', VENV_DIRS, INI_FILES)
                invoke_virtualenv(virtualenv_run_path, args.python,
                                  ini_load_path, interactive_load_path, cwd)
            if args.freeze:
                pip('bin/pip',
                    ini_load_path,
                    PKG_REQUIREMENT_FILEPATHS,
                    PKG_CONSTRAINT_FILEPATHS,
                    cwd,
                    action='freeze')
                exit(0)

            files_exist = [exists(entry) for entry in VENV_DIRS | INI_FILES]
            if not all(files_exist):
                # at least one virtualenv dir missing
                if any(files_exist):
                    destroy('incomplete virtualenv detected', VENV_DIRS,
                            INI_FILES)
                else:
                    print('no virtual env detected')
                invoke_virtualenv(virtualenv_run_path, args.python,
                                  ini_load_path, interactive_load_path, cwd)

            # always try to install the requirements.
            pip('bin/pip3',
                ini_load_path,
                PKG_REQUIREMENT_FILEPATHS,
                PKG_CONSTRAINT_FILEPATHS,
                cwd,
                parallel=args.parallel,
                easy_install_proxy=args.easy_install_proxy,
                action='install')

    except RuntimeError as err:
        optparser.error(
            '%s Destination virtualenv directory and Python interpreter must both exist !!'
            % (str(err)))


if __name__ == '__main__':
    main()
